Fix Event content type (#16)
kitconcept/volto-light-theme pull request #124
Opened 2023-07-03 08:48 UTC by iRohitSingh

<img width="888" alt="Screenshot 2023-07-03 at 14 18 18" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/c438a3b0-36d2-4bdc-b648-49c20efe8201">

2023-07-03 09:12 UTC, steffenri commented
@sneridagh Should we also add the head_title here? In the same line as the date. What do you think?

2023-07-04 15:06 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                    locale: deLocale,
@iRohitSingh I'm pretty sure we also want to have an english fallback here.. Especially since english dates and times are displayed in a different way than german ones.
Could you add that?

@sneridagh Also, are we still using date-fns? I though we did get rid of this.

2023-07-04 15:06 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                    locale: deLocale,
Same here.

2023-07-05 09:46 UTC, sneridagh requested changes
@iRohitSingh yeah, we don't use date-fns anymore... in fact it's use is discouraged. Vanilla JS is better nowadays. 

In core we have a helper component `FormattedDate`. It is documented and has a StoryBook story.

Also, can you add a screenshot of the outcome? The one you included do not have the requirements met:

<img width="693" alt="image" src="https://github.com/kitconcept/volto-light-theme/assets/486927/1b573fa3-91b6-4323-934c-93fcd5c8881a">

2023-07-06 12:41 UTC, iRohitSingh commented
> @iRohitSingh yeah, we don't use date-fns anymore... in fact it's use is discouraged. Vanilla JS is better nowadays.
> 
> In core we have a helper component `FormattedDate`. It is documented and has a StoryBook story.
> 
> Also, can you add a screenshot of the outcome? The one you included do not have the requirements met:
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/486927/251110372-1b573fa3-91b6-4323-934c-93fcd5c8881a.png">

If you see the figma the above screenshot is coming after some block. I don't know after how many block I have to show this view. Can you please clarify for me. cc @steffenri

2023-07-06 13:51 UTC, iRohitSingh commented
<img width="871" alt="Screenshot 2023-07-06 at 19 21 09" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/dd1b65fd-b4df-40d2-ab1f-88be552454bc">

2023-07-07 08:54 UTC, sneridagh commented
@steffenri @iRohitSingh I will talk to Thomas, let's put this block of text at the beginning after the title, then the rest of the blocks (in the Event content type). We did that before in FZJ or DLR. @iRohitSingh please take a look how the customizations are done, and follow the pattern.

2023-07-09 16:46 UTC, iRohitSingh commented
<img width="950" alt="Screenshot 2023-07-09 at 22 15 43" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/ecaf5d09-8b4b-4ae7-93c4-406ee912ba27">

2023-07-09 16:50 UTC, iRohitSingh commented
@steffenri  I am not able to find VERANSTALTER data for this field and Jetzt anmelden and this . Everything else is good from my side. please review it properly and make comment if anything is off.

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                  UHR
@iRohitSingh Missing english part.

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                  <FormattedDate date={content?.end} format={dateOptions} /> UHR
same here

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                      {content.description && (
@iRohitSingh Remove this please. We never show any descriptions on any contenttype and we should be consistent.

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                  Uhr
@iRohitSingh Missing english part

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                  Uhr
same here

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                  Veranstaltungsort
same here

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                        Tel.{' '}
translations

2023-07-11 09:10 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                              Jetzt anmelden
translations

2023-07-11 09:20 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                  UHR
@steffenri formatted date component takes care of english part.

2023-07-11 09:20 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                  <FormattedDate date={content?.end} format={dateOptions} /> UHR
@steffenri formatted date component takes care of english part.

2023-07-11 09:21 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Uhr
@steffenri formatted date component takes care of english part.

2023-07-11 09:22 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Musterevents GmbH
see my comment I don't able to find the data from backend

2023-07-11 13:19 UTC, iRohitSingh commented
Pr of example content in bfs https://github.com/kitconcept/bfs-intranet/pull/166

2023-07-11 13:20 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                    locale: deLocale,
done

2023-07-11 13:21 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Uhr
done

2023-07-11 13:24 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                      {content.description && (
done

2023-07-11 13:24 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Uhr
done

2023-07-11 13:24 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Veranstalter-website
done

2023-07-11 13:24 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Musterevents GmbH
removed

2023-07-11 13:25 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                        Tel.{' '}
In both german and english tel is tel but if you want to add translation please tell me the translation.

2023-07-11 13:25 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                              Jetzt anmelden
removed we don't habe data.

2023-07-11 13:26 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  ANsprechpERSON
done

2023-07-11 13:26 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Veranstaltungsort
done

2023-07-11 13:26 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                  Veranstalter
done

2023-07-11 14:35 UTC, steffenri requested changes

2023-07-11 14:35 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                    id=" Organizer-website"
@iRohitSingh "Website" is enough here.

2023-07-11 14:35 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                    id=" Contact-person"
@iRohitSingh "Contact" here.

2023-07-11 14:35 UTC, steffenri commented on src/components/Theme/EventView.jsx
> +                                          id="Tel."
"Phone" please

2023-07-11 14:56 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                    id=" Contact-person"
done

2023-07-11 14:57 UTC, iRohitSingh commented on src/components/Theme/EventView.jsx
> +                                    id=" Organizer-website"
done

2023-07-11 14:57 UTC, iRohitSingh commented
@steffenri Before merging pr please add missing translation in German

2023-07-12 07:45 UTC, merged