Event View re-implementation
kitconcept/volto-light-theme pull request #169
Opened 2023-07-20 11:37 UTC by iFlameing

Screenshot

![Screenshot 2023-07-20 at 4 52 06 PM](https://github.com/kitconcept/volto-light-theme/assets/33936987/e153d847-7302-4f83-ac91-94a2239c8b8e)
![Screenshot 2023-07-20 at 4 51 23 PM](https://github.com/kitconcept/volto-light-theme/assets/33936987/e81e1247-a87d-4c3f-9427-ddb79edf8c70)

2023-07-20 11:44 UTC, iFlameing commented on src/theme/_content.scss
> +          font-size: 24px;
I am not using mixing here because we don't have any mixing which satisfies this behavior. regarding font-size, font-weight, and line height.

2023-07-20 13:18 UTC, iFlameing commented
@sneridagh @steffenri From my side everything is complete.

2023-07-21 08:06 UTC, sneridagh requested changes

2023-07-21 08:06 UTC, sneridagh commented on src/theme/_content.scss
> +  @media only screen and (max-width: 768px) {
Ok, but do not use fixed media queries, please. There's variables for that.

2023-07-24 08:00 UTC, sneridagh commented
@iFlameing please comments.

2023-07-24 10:34 UTC, iFlameing commented on src/theme/_content.scss
> +  @media only screen and (max-width: 768px) {
sorry! I should have seen in my review. Thanks for pointing it out. Now resolved.

2023-07-24 10:34 UTC, iFlameing commented
@sneridagh done. Regarding force pushed I missed to do the pull before merging master  locally. sorry! for that.

2023-07-24 10:35 UTC, iFlameing commented
And I never work on `fatal: Need to specify how to reconcile divergent branches.`

on this error. Do you know something about this how I can reconcile.

2023-07-25 14:36 UTC, sneridagh requested changes

2023-07-25 14:36 UTC, sneridagh commented on src/theme/_content.scss
> +  @media only screen and (max-width: $tablet-breakpoint) {
@iFlameing make sure this cannot be done better with a container query.

2023-07-26 09:31 UTC, sneridagh approved these changes

2023-07-26 09:31 UTC, merged