overwrite icons, default image & minor sizing fixes
kitconcept/volto-light-theme pull request #207
Opened 2023-08-08 18:42 UTC by danalvrz

- Overwrite sorting icons
- Overwrite default image for Listings
- Fix image fit for Listing Grid variation
- Replace container query with media query to fix image sizing for tablet when sidebar is open

2023-08-08 19:40 UTC, davisagli requested changes

2023-08-08 19:40 UTC, davisagli commented on src/theme/blocks/_listing.scss
> +}
@danalvrz Tell me more about where this is solving a problem. At first glance it looks way too general for me to be confident it won't cause problems elsewhere.

2023-08-08 19:40 UTC, davisagli commented on src/theme/blocks/_search.scss
> +        aspect-ratio: $aspect-ratio;
@danalvrz I think we should add `object-fit: cover` here, to make sure the default image fills the space when the project is using a different aspect ratio.

Screenshots from our project using 4/3... Without it:
<img width="990" alt="Screenshot 2023-08-08 at 12 30 57 PM" src="https://github.com/kitconcept/volto-light-theme/assets/49014/27ea4f01-66a1-4a9b-83cf-86f66fd92c3b">

With `object-fit: cover`:
<img width="984" alt="Screenshot 2023-08-08 at 12 31 03 PM" src="https://github.com/kitconcept/volto-light-theme/assets/49014/ef3d61da-fb14-4eea-8914-d627e7265d5e">

2023-08-08 19:40 UTC, davisagli commented on src/theme/blocks/_search.scss
> +        @media only screen and (max-width: $largest-mobile-screen) {
@danalvrz Why'd you change it to use a media query instead of a container query?

2023-08-08 20:32 UTC, danalvrz commented on src/theme/blocks/_listing.scss
> +}
I moved the rule inside the Search block, I think it is better. This is the issue generated by the rule coming from semantic ui:
<img width="1015" alt="Screenshot 2023-08-08 at 14 10 32" src="https://github.com/kitconcept/volto-light-theme/assets/89805481/4dc85c2f-aaa8-4e9c-9ca3-24533fef530e">

2023-08-08 20:33 UTC, danalvrz commented on src/theme/blocks/_search.scss
> +        aspect-ratio: $aspect-ratio;
I added the `object-fit: cover` to all images inside a Listing, which applies to the Search results as well

2023-08-08 20:33 UTC, davisagli commented on src/theme/blocks/_listing.scss
> +}
@danalvrz Got it. Looks safer now

2023-08-08 20:33 UTC, danalvrz commented on src/theme/blocks/_search.scss
> +        @media only screen and (max-width: $largest-mobile-screen) {
When in Tablet view, if you open the sidebar the container query triggers the `width: 100%`, breaking the layout for the images. If it is a media query, the screen size remains the same and the width change is not triggered:
<img width="1281" alt="Screenshot 2023-08-08 at 14 24 16" src="https://github.com/kitconcept/volto-light-theme/assets/89805481/1cfea127-85df-45d4-b00f-65d0b9fb4ef7">

2023-08-08 20:35 UTC, davisagli commented on src/theme/blocks/_search.scss
> +        aspect-ratio: $aspect-ratio;
@danalvrz Okay. How come the search block has some unique image styles here? In general listings in the search block are supposed to look the same as the listing block.

2023-08-08 20:40 UTC, davisagli commented on src/theme/blocks/_search.scss
> +        @media only screen and (max-width: $largest-mobile-screen) {
@danalvrz Well, the point of the container query is to style things based on the actual size of the content area (what is left without counting the width of the sidebars). If that width is less than the mobile breakpoint width, then I would expect to see the mobile styles, even if the viewport width is still within the tablet range.

Here, it looks like the actual problem is that the mobile width inside the container is not styled to match the design (images are not supposed to be 100% width there):
<img width="409" alt="Screenshot 2023-08-08 at 1 38 48 PM" src="https://github.com/kitconcept/volto-light-theme/assets/49014/d3607c82-7fee-4f93-b92c-1fcfcb4b721e">

https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Volto-Light-Theme?type=design&node-id=4069-35606&mode=dev

2023-08-08 20:53 UTC, danalvrz commented on src/theme/blocks/_search.scss
> +        @media only screen and (max-width: $largest-mobile-screen) {
good point, let's leave it as a container query. We also should fix the order of the elements in mobile ( heading -> image -> description). I'll work on it.

2023-08-08 20:55 UTC, danalvrz commented on src/theme/blocks/_search.scss
> +        aspect-ratio: $aspect-ratio;
I deleted the styles for the images inside the Search block, they are not needed, and were basically duplicates of what we have for images in the Listings

2023-08-11 21:20 UTC, danalvrz commented on src/theme/blocks/_search.scss
> +        @media only screen and (max-width: $largest-mobile-screen) {
Fixed to match updated design: https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Volto-Light-Theme?node-id=4773%3A65840&mode=dev

<img width="535" alt="Screenshot 2023-08-11 at 15 19 40" src="https://github.com/kitconcept/volto-light-theme/assets/89805481/9f701c98-c0ea-468c-b7c7-b5048240dceb">

2023-08-11 21:27 UTC, danalvrz commented on src/theme/blocks/_search.scss
> +        aspect-ratio: $aspect-ratio;
Example project using 4/3:
![Screenshot 2023-08-11 at 15-25-49 Block Auflistung (Listing)](https://github.com/kitconcept/volto-light-theme/assets/89805481/005e9f88-f201-486c-90a9-87efec342fa5)

2023-08-15 16:56 UTC, davisagli commented on src/theme/_layout.scss
> +  & > .block.search .emptyListing,
@danalvrz This is okay, but it makes me think that maybe we should put one container inside the grid block markup so that we don't need so many different CSS rules.

2023-08-15 16:56 UTC, davisagli commented on src/theme/blocks/_search.scss
> +      &:last-child:not(.facets) {
This will expand out to some weird CSS like: `.facets:last-child:not(.facets)`. It would be better to repeat `.listing.message` and `.listing-item` in the scss so that the CSS rules are added for them only.

2023-08-15 16:56 UTC, davisagli commented on src/theme/blocks/_listing.scss
> +  }
@danalvrz It looks like this is causing a misalignment of the facets

<img width="463" alt="Screenshot 2023-08-15 at 9 55 02 AM" src="https://github.com/kitconcept/volto-light-theme/assets/49014/94e24794-1967-4ca8-b149-7883244a8630">

2023-08-15 20:18 UTC, danalvrz commented on src/theme/_layout.scss
> +  & > .block.search .emptyListing,
I agree that it would be better to have a container for it. I'll make a ticket about it.

2023-08-15 20:32 UTC, davisagli commented on src/theme/_layout.scss
> +  & > .block.search .emptyListing,
@danalvrz Perfect. It doesn't need to be solved in this PR as long as we have a ticket to come back to

2023-08-15 22:10 UTC, davisagli commented on news/207.bugfix
> +Add icons and default image customizations, fix other small image sizing issues for Listings. @danalvrz
```suggestion
Add icons and default image customizations, fix other small image sizing issues for Listings, fix spacing issues for Search block. @danalvrz
```

2023-08-15 22:10 UTC, davisagli approved these changes

2023-08-15 22:21 UTC, merged