Fat menu and mobile menu implementation.
kitconcept/volto-light-theme pull request #237
Opened 2023-09-22 14:13 UTC by iFlameing

2023-09-22 14:18 UTC, iFlameing commented on src/components/MobileNavigation/MobileNavigation.jsx
> +              ? '/de/service/barrierefreiheit'
I need to remove dlr specific code.

2023-09-22 14:20 UTC, iFlameing commented on src/components/Navigation/Navigation.jsx
> +      let adjustedPathName = pathname;
we don't need this in volto-light-theme.

2023-09-22 14:20 UTC, iFlameing commented on src/components/Navigation/Navigation.jsx
> +          getBaseUrl(adjustedPathName),
same here.

2023-09-22 14:20 UTC, iFlameing commented on src/components/Navigation/Navigation.jsx
> -    if (e.key && e.key !== 'Enter') {
add this behaviour.

2023-09-25 12:13 UTC, iFlameing commented on src/components/Navigation/Navigation.jsx
> -    if (e.key && e.key !== 'Enter') {
done.

2023-09-26 14:55 UTC, iFlameing commented
@sneridagh Ready for first review from my side. I tried to fix as much code as possible, but please review css code.

Also I am not able to fix the fatmenu in Edit mode. I don't want to write css for specific cases. Please try it once locally and review it.

2023-11-07 12:43 UTC, sneridagh commented
@iFlameing I can see the menu a bit shifted up:

<img width="627" alt="image" src="https://github.com/kitconcept/volto-light-theme/assets/486927/5bd48092-5d8a-4353-8fcd-49a553f3bb57">

Regarding the edit, I won't display it, just disable it. There's no point to display it in there.

2023-11-07 12:49 UTC, sneridagh requested changes
@iFlameing I can see the menu a bit shifted up:

<img width="627" alt="image" src="https://github.com/kitconcept/volto-light-theme/assets/486927/5bd48092-5d8a-4353-8fcd-49a553f3bb57">

Regarding the edit, I won't display it, just disable it. There's no point to display it in there.

2023-11-07 15:07 UTC, iRohitSingh commented
<img width="639" alt="Screenshot 2023-11-07 at 8 37 02 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/22a9dabd-c0a9-4000-bebd-c9c01ecaec53">


<img width="824" alt="Screenshot 2023-11-07 at 8 37 31 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/9577496f-bc6a-4f8e-99f4-d0a4f5f4b7ea">

2023-11-07 18:51 UTC, iRohitSingh commented
@sneridagh I don't know why I am getting these linting problem in my new laptop. I ran the make format still I am getting error.

2023-11-08 09:29 UTC, sneridagh commented
@iRohitSingh I had to fix the height of the overall header was a bit off, that's why it wasn't looking well (I know only a few pixels), but still... but now the menu and the underline are a bit off again :slightly_smiling_face: could you please fix it?

2023-11-08 10:05 UTC, iRohitSingh commented
@sneridagh Fixed.

<img width="989" alt="Screenshot 2023-11-08 at 3 33 08 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/b2969bc2-489d-433b-9be1-027c2f4ffabb">


<img width="978" alt="Screenshot 2023-11-08 at 3 33 54 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/68cdb0cb-d038-437b-a133-8691f79411ac">

Add page.
<img width="1102" alt="Screenshot 2023-11-08 at 3 34 46 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/dccf04f1-cb63-4cc7-9a55-ea07868457e0">

2023-11-08 13:48 UTC, steffenri commented on src/components/Navigation/Navigation.jsx
> +  componentWillUnmount() {
Can you give me an estimate on how much work it would be to refactor?

2023-11-08 15:00 UTC, iFlameing commented on src/components/Navigation/Navigation.jsx
> +  componentWillUnmount() {
approx 1 to 2 days.  Lot's of edge case and check everything one more time,

2023-11-08 15:01 UTC, steffenri commented on src/components/Navigation/Navigation.jsx
> +  componentWillUnmount() {
@sneridagh Please decide if that's worth the effort.

2023-11-08 15:02 UTC, iFlameing commented on src/components/MobileNavigation/MobileNavigation.jsx
> +      body.style.position = 'fixed';
There are no other options than this.  We want this behavior for the mobile menu and we can only do it by js manipulation. Before react you not only do for style but also for appending div and section also. Just think how cumbersome it was before.

2023-11-08 15:03 UTC, iFlameing commented on src/components/MobileNavigation/MobileNavigation.jsx
> +import { Button } from 'semantic-ui-react';
ok, I will do that or @iRohitSingh will do it.

2023-11-10 08:06 UTC, sneridagh commented on src/components/MobileNavigation/MobileNavigation.jsx
> +      body.style.position = 'fixed';
You can also inject a className ;) I think that is what I was doing in zeelandia and other projects.

2023-11-10 08:06 UTC, sneridagh commented on src/components/MobileNavigation/MobileNavigation.jsx
> +import { Button } from 'semantic-ui-react';
Yes, please NO semantic UI anymore in our projects, please.

2023-11-10 08:07 UTC, sneridagh commented on src/components/Navigation/Navigation.jsx
> +  componentWillUnmount() {
In fact, in Volto it is already one (Tisha GSOC), so it will be easier than that. Could you please take care?

2023-11-10 08:10 UTC, sneridagh requested changes
Please take a look at the comments.

2023-11-10 08:16 UTC, iRohitSingh commented on src/components/Navigation/Navigation.jsx
> +  componentWillUnmount() {
@sneridagh I don't understand what do you mean by 'in volto it is already one'. Do we have fatmenu in volto ?  I don't think so. can you please explain what you want to say please.

2023-11-14 15:33 UTC, steffenri requested changes

2023-11-14 15:33 UTC, steffenri commented on src/components/MobileNavigation/MobileNavigation.jsx
>                  basic
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/MobileNavigation/MobileNavigation.jsx
>                  icon
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/MobileNavigation/MobileNavigation.jsx
>                              basic
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/MobileNavigation/MobileNavigation.jsx
>                              icon
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/MobileNavigation/MobileNavigation.jsx
>                                          basic
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/MobileNavigation/MobileNavigation.jsx
>                                          icon
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/Navigation/Navigation.jsx
> +        stackable
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/Navigation/Navigation.jsx
> +        pointing
This won't have any effect. Please remove.

2023-11-14 15:33 UTC, steffenri commented on src/components/Navigation/Navigation.jsx
> +        secondary
This won't have any effect. Please remove.

2023-11-15 09:49 UTC, iRohitSingh commented on src/components/Navigation/Navigation.jsx
> +        secondary
Fixed

2023-11-15 09:49 UTC, iRohitSingh commented on src/components/Navigation/Navigation.jsx
> +        stackable
Fixed

2023-11-15 09:49 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
>                                          icon
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
>                                          basic
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
>                              icon
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
>                              basic
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
>                  icon
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
>                  basic
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/Navigation/Navigation.jsx
> +  componentWillUnmount() {
Fixed

2023-11-15 09:50 UTC, iRohitSingh commented on src/components/MobileNavigation/MobileNavigation.jsx
> +import { Button } from 'semantic-ui-react';
Fixed

2023-11-15 12:42 UTC, iRohitSingh commented
<img width="1470" alt="Screenshot 2023-11-15 at 5 07 58 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/6f666b3b-6fa8-44e5-940d-c210e948e834">

2023-11-16 10:23 UTC, merged

2024-01-10 23:27 UTC, danalvrz commented on src/theme/_header.scss
> +      border-bottom: 9px solid transparent;
@iFlameing @sneridagh @iRohitSingh why do we need this transparent border? Couldn't we instead set https://github.com/kitconcept/volto-light-theme/blame/bcb4262a54d1c51aba83ba552c70d25b34f535c3/src/theme/_header.scss#L287 to -40px? 
<img width="1096" alt="Screenshot 2024-01-10 at 5 26 25 p m" src="https://github.com/kitconcept/volto-light-theme/assets/89805481/377ae0a0-5024-42b9-936a-53d7466866bd">

2024-01-11 11:34 UTC, iRohitSingh commented on src/theme/_header.scss
> +      border-bottom: 9px solid transparent;
As you can clearly see if we don't give the border 9px  transparent we wll not get the desired the space between navigation and fatmenu which is 35px according to figma. 


<img width="1177" alt="Screenshot 2024-01-11 at 4 34 10 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/4c62c690-1871-4023-ba21-1d13ada3f5b5">

Also if you see submenu-wrapper has a marign-top 40px. So if you don't give the border 9px then we will be short of space.

You are right if we don't want this transparent border we have to do these changes.

1. Give submenu-wrapper margin 49px.
2. remove the border-bottom 
3. make it 40px before.

But there is also other region see this screenshot

<img width="1470" alt="Screenshot 2024-01-11 at 5 00 17 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/3bd90bf4-0017-47a3-9b61-36a303ccf616">

this is example of demo plone org. we use the the border bottom to show a active one. I think this is why we use that. I am just giving you cases that how it landed in there. Not a correct description why we did that in first place.

2024-01-11 15:57 UTC, danalvrz commented on src/theme/_header.scss
> +      border-bottom: 9px solid transparent;
@iRohitSingh thanks for the answer! In general, creating spacing with transparent lines seems odd, but I get the use case here. Maybe we can revisit this at some point in volto, and change the approach.