Fix css of Sitemap(#209)
kitconcept/volto-light-theme pull request #259
Opened 2023-11-09 11:28 UTC by iRohitSingh

Fix #209 

<img width="1184" alt="Screenshot 2023-11-09 at 4 57 49 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/11edffcd-dc01-4456-8a65-6f3b4ffa5abc">

2023-11-09 11:40 UTC, iRohitSingh commented
@sneridagh I have appllied the css for sitemap but it is not center to the container.


<img width="1470" alt="Screenshot 2023-11-09 at 5 09 00 PM" src="https://github.com/kitconcept/volto-light-theme/assets/61353484/bfdf3926-7d5b-4997-9015-a14f0463ea63">

2023-11-16 10:26 UTC, sneridagh requested changes
@iRohitSingh probably the container it's using is the wrong (Volto's) one. Take a look at

https://github.com/plone/volto/blob/ad9e98633c68d810b0201ba4e9e1c9c8b83e16cf/src/components/theme/View/LinkView.jsx#L25

2023-11-17 15:10 UTC, iRohitSingh commented
> @iRohitSingh probably the container it's using is the wrong (Volto's) one. Take a look at
> 
> https://github.com/plone/volto/blob/ad9e98633c68d810b0201ba4e9e1c9c8b83e16cf/src/components/theme/View/LinkView.jsx#L25

@sneridagh regarding this comment even our new a container with default container width applied look like this which is not looking good. can we ask our designer for mockup and then implement it?

![Screenshot 2023-11-17 at 5 24 41 PM](https://github.com/kitconcept/volto-light-theme/assets/61353484/f8dd3380-6889-4fe4-a6aa-550020174e43)

2023-11-20 08:39 UTC, ichim-david commented on src/theme/main.scss
> +@import 'sitemap';
@iRohitSingh @sneridagh  I thought tat addonsThemeCustomizationMain should be the last import in order to get modification from other addons, thus the sitemap import shouldn't be placed here

2023-11-20 08:55 UTC, sneridagh commented on src/theme/main.scss
> +@import 'sitemap';
@ichim-david it is... good catch. @iRohitSingh there can't be anything from that onwards.

2023-11-20 09:05 UTC, sneridagh commented on src/theme/main.scss
> +@import 'sitemap';
@ichim-david fixed. @iRohitSingh please take alook that all is good now.

2023-11-20 09:19 UTC, sneridagh requested changes

2023-11-20 09:19 UTC, sneridagh commented on src/theme/_sitemap.scss
> +      line-height: 77px;
Why are we not using the corresponding mixin from the theme for h1?

2023-11-20 09:25 UTC, sneridagh commented on src/theme/_sitemap.scss
> +      line-height: 77px;
why this need to be redefined?

2023-11-21 11:56 UTC, iRohitSingh commented on src/theme/_sitemap.scss
> +      line-height: 77px;
Fixed

2023-11-28 10:52 UTC, merged