Grid theme style
kitconcept/volto-light-theme pull request #30
Opened 2023-01-05 00:27 UTC by danalvrz

Issue -> https://github.com/kitconcept/bfs-intranet/issues/16

2023-01-06 17:13 UTC, davisagli commented on src/theme/blocks/_grid.scss
> +  }
@danalvrz I see why you are setting the widths like this (to make space for the gutter, since the slate block has its own padding that is unrelated to the grid columns). But I don't particularly like it. In DLR, we avoid this by adding another div wrapped around the slate block (https://github.com/kitconcept/dlr-internet/blob/main/frontend/src/addons/volto-dlr/src/index.js#L358). So we can keep the normal column widths, and then apply the background and padding on that additional wrapper.

It's probably worth checking with @sneridagh whether this is still the best way to go.

2023-01-11 16:49 UTC, sneridagh requested changes

2023-01-11 16:49 UTC, sneridagh commented on src/components/Blocks/Teaser/schema.js
> +  schema.properties.styles.schema.fieldsets[0].fields = ['align'];
This is no longer needed since in @kitconcept/volto-blocks-grid the align styling button included in there. Maybe you have to merge the main branch again?

2023-01-11 16:49 UTC, sneridagh commented on src/customizations/volto/components/manage/Blocks/StyleWrapper.jsx
> +/**
I'd like to maintain this customisation out of the way until it's really necessary. I hoped to be able to get along without it, but could be that we need it anyways. 

@danalvrz why do you need it? which use case?

Also this helper was refactored for Volto 16, so it has to be adapted before including it.

2023-01-11 17:00 UTC, danalvrz commented on src/customizations/volto/components/manage/Blocks/StyleWrapper.jsx
> +/**
It was implemented to avoid having to set different widths to the columns in the grid, for example when adding a 2 column grid with 2 slate blocks next to each other.

<img width="744" alt="Screenshot" src="https://user-images.githubusercontent.com/89805481/211869152-abead9d7-72a1-4037-8e04-f147690075b8.png">

 My first approach was to hard code widths (49% instead of 50%) that allow a gutter between them. The comment above is related to this point (https://github.com/kitconcept/volto-light-theme/pull/30#discussion_r1063621999) If there's a better way I can update it

2023-01-11 17:02 UTC, davisagli commented on src/customizations/volto/components/manage/Blocks/StyleWrapper.jsx
> +/**
@danalvrz No -- that's what we used the ExtraAlignWrapper for, but I don't think we need the StyleWrapper.

2023-01-11 17:03 UTC, danalvrz commented on src/customizations/volto/components/manage/Blocks/StyleWrapper.jsx
> +/**
Got it, I was confusing them. I will take a look and remove it then

2023-01-12 18:37 UTC, davisagli approved these changes
We still need to figure out what to do with the background colors, but I think it's a good step in the right direction.

2023-01-12 18:38 UTC, davisagli commented
@sneridagh ok to merge now?

2023-01-13 11:09 UTC, sneridagh approved these changes

2023-01-13 11:09 UTC, merged