fix Logo alt-Title + add German translations
kitconcept/volto-light-theme pull request #337
Opened 2024-02-01 12:23 UTC by Molochem

Fixed the Logo-Alt Title to display "Back to homepage", added fitting Translations. Also added a Lot of missing German Translations to `locales/de/LC_MESSAGES/volto.po` i noticed.

2024-02-01 21:28 UTC, davisagli requested changes
Based on the discussion in https://github.com/plone/volto/pull/5722, this should either say "Visit home page" or use the title of the site.

2024-02-01 22:14 UTC, stevepiercy commented
See [discussion on the reopened issue](https://github.com/plone/volto/issues/5720#issuecomment-1922358578) for a single place to discuss how to proceed for this issue.

2024-03-06 09:33 UTC, sneridagh commented
@Molochem needs to be adjusted, right?

2024-04-26 08:47 UTC, sneridagh commented
@Molochem please update it with the latests developments in Volto.

2024-05-27 09:20 UTC, sneridagh commented
@jonaspiterek could you please take over?

2024-06-03 09:59 UTC, sneridagh approved these changes

2024-06-03 09:59 UTC, merged

2024-06-03 14:00 UTC, davisagli commented on packages/volto-light-theme/src/components/Logo/Logo.jsx
> +        title={intl.formatMessage(messages.homepage)}
@sneridagh @Molochem This approach is not correct based on the discussion in https://github.com/plone/volto/issues/5720#issuecomment-1956657437

- Neither the link nor the img should have `title`
- The link should have `aria-label="Home"`
- The img should have `alt="Logo"`