Backport Search block from dlr
kitconcept/volto-light-theme pull request #35
Opened 2023-01-09 11:43 UTC by iFlameing

2023-01-09 18:53 UTC, davisagli requested changes

2023-01-09 18:53 UTC, davisagli commented on src/components/Blocks/Search/TopSideFacets.jsx
> +import { Grid } from 'semantic-ui-react';
@iFlameing For the volto-light-theme we are not using Semantic UI (see: https://github.com/kitconcept/volto-light-theme#it-should-not-use-any-semanticui-component-or-styling)

@sneridagh Can you make a suggestion how to handle the width of the facet columns instead?

2023-01-09 18:53 UTC, davisagli commented on src/theme/blocks/_search.scss
> +      @media only screen and (max-width: 786px) {
All the media queries should use the variables for the breakpoints, instead of hardcoding it

2023-01-10 08:46 UTC, steffenri commented on src/components/Blocks/Search/TopSideFacets.jsx
> +import { Grid } from 'semantic-ui-react';
@iFlameing You can use the browser css grid option. That should require only some lines of css and a little bit more QA.

2023-01-13 11:20 UTC, sneridagh reviewed
I left some comments.

https://github.com/kitconcept/volto-light-theme/issues/41

2023-01-13 11:20 UTC, sneridagh commented on src/components/Blocks/Search/TopSideFacets.jsx
> +import { Grid } from 'semantic-ui-react';
The Grid component is one of the basic structural components that we should provide out of any specific design system. There is a bunch of them that I have in mind. I will look to define the list of what we need the next week.

However, since we are dealing with a customisation from a component of Volto itself, and this is not going to change anytime soon, we should proceed with using the SemanticUI one. Once Volto makes the switch, we can update all the customizations. Good thing is that they are all controlled in the `customization` folder. I'll add it to the documentation.

2023-01-13 11:20 UTC, sneridagh commented on src/theme/blocks/_search.scss
> +      @media only screen and (max-width: 786px) {
@iFlameing we don't have access to the breakpoints in the default theme here, but we should come up with our own. I'll add a ticket, so you can use them.

2023-01-13 11:23 UTC, sneridagh commented on src/theme/blocks/_search.scss
> +      @media only screen and (max-width: 786px) {
https://github.com/kitconcept/volto-light-theme/issues/41

2023-01-13 11:23 UTC, sneridagh commented on src/components/Blocks/Search/TopSideFacets.jsx
> +import { Grid } from 'semantic-ui-react';
https://github.com/kitconcept/volto-light-theme/blob/main/README.md#volto-components-customizations-use-case

2023-01-16 09:28 UTC, sneridagh commented
@iFlameing please complete this with the comments.

2023-01-18 13:17 UTC, iFlameing commented
Started working on this.

2023-01-18 14:47 UTC, iFlameing commented on src/theme/blocks/_search.scss
> +      @media only screen and (max-width: 786px) {
done

2023-01-18 14:48 UTC, iFlameing commented
@sneridagh ready for review.

2023-01-19 11:40 UTC, merged