New docs
kitconcept/volto-light-theme pull request #423
Opened 2024-10-24 12:12 UTC by sneridagh

2024-10-24 19:42 UTC, davisagli reviewed
@sneridagh Don't most of these new how-to docs belong in volto's docs rather than in volto-light-theme?

2024-10-28 17:14 UTC, davisagli commented on README.md
> +You can find the documentation of this package in: https://volto-light-theme.readthedocs.io
We should also remove some of the info below that is now included in the docs (but I guess only after the RTD site is fully deployed)

2024-10-28 17:14 UTC, davisagli commented on README.md
> +You can find the documentation of this package in: https://volto-light-theme.readthedocs.io
For one thing, the Installation section below is not up to date with what you added in the new docs.

2024-11-04 12:41 UTC, sneridagh commented
@davisagli I've amended the docs, so this PR should go first before #420

2024-11-05 20:59 UTC, davisagli approved these changes
@sneridagh Basically looks good to me.

2024-11-05 20:59 UTC, davisagli commented on docs/install.md
> +This versions are orientative, and up to date as per 2024-11-04.
I'm not sure what orientative means.

2024-11-05 22:57 UTC, stevepiercy commented on docs/install.md
> +This versions are orientative, and up to date as per 2024-11-04.
I think he put it there by occident.

2024-11-07 07:31 UTC, stevepiercy requested changes

2024-11-07 07:31 UTC, stevepiercy commented on docs/compatibility.md
> +| 5.x.x       |   >= Volto 17.18.0 or >=Volto 18.0.0-alpha.36  |
Should this be extended with v6?

2024-11-07 07:31 UTC, stevepiercy commented on docs/conf.py
> +    release = "17.15.6"
Verify that the version and release are correct.

2024-11-07 07:31 UTC, stevepiercy commented on docs/contributing.md
> +Start the Cypress interactive test runner.
In which terminal session? First or second?

2024-11-07 07:32 UTC, stevepiercy approved these changes
I've completed my review by pushing commits. I left a few comments for consideration. Otherwise it is good to merge, and we can check RTD to verify it works.

2024-11-07 07:40 UTC, stevepiercy commented on docs/install.md
> +This versions are orientative, and up to date as per 2024-11-04.
I rewrote this in https://github.com/kitconcept/volto-light-theme/pull/423/commits/0a6d4feecc6b66dc9c334a0db1c94b0bae4dade6

2024-11-07 11:48 UTC, merged

2024-11-07 11:48 UTC, sneridagh commented
@stevepiercy thanks!!

2024-11-07 11:51 UTC, stevepiercy commented
Let's verify that the home page URL is correct.

https://volto-light-theme.readthedocs.io/

https://volto-light-theme.readthedocs.io/sitemap.xml

https://volto-light-theme.readthedocs.io/robots.txt

Oopsie, one mistake. PR incoming. No changelog needed.