fix: #438 External URL icon has strange underline
kitconcept/volto-light-theme pull request #439
Opened 2024-12-04 04:59 UTC by Tishasoumya-02

<img width="516" alt="image" src="https://github.com/user-attachments/assets/c731a051-9163-4c55-b057-5fb9379be867">

2024-12-04 05:22 UTC, stevepiercy approved these changes
Looks much better. Thank you!

2024-12-04 09:40 UTC, stevepiercy requested changes

2024-12-04 09:40 UTC, stevepiercy commented on packages/volto-light-theme/news/439.bugfix
> +External URL icon has strange underline fix #438  @Tishasoumya-02
```suggestion
Removed the non-breaking space from the external URL icon, removing the strange underline. @Tishasoumya-02
```

2024-12-04 09:40 UTC, stevepiercy commented on packages/volto-light-theme/news/439.bugfix
This file should be named after the number of the issue fixed, if present, else the pull request. I'd change it to `438.bugfix`, but it's fine as is, too.

2024-12-04 09:58 UTC, stevepiercy commented
Although unrelated to this PR, there is a failing build now when it was not failing before at https://github.com/kitconcept/volto-light-theme/actions/runs/12153651828/job/33901673414#step:8:324. I have no idea how to fix that. I compared a successful build to a failed one, and see that failed builds mention this:

```console
> @plone/components@2.1.1 build /home/runner/work/volto-light-theme/volto-light-theme/core/packages/components
> tsup && pnpm build:css

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
CLI Using tsup config: /home/runner/work/volto-light-theme/volto-light-theme/core/packages/components/tsup.config.ts
CLI Target: es2022
CLI Cleaning output folder
CJS Build start
ESM Build start
CJS dist/index.cjs 162.26 KB
CJS ⚡️ Build success in 149ms
ESM dist/index.js 133.94 KB
ESM ⚡️ Build success in 156ms
DTS Build start
Error: src/components/Checkbox/Checkbox.tsx(15,9): error TS2322: Type '{ children: (string | number | boolean | Element | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ((values: CheckboxRenderProps & { ...; }) => ReactNode) | null | undefined)[]; }' is not assignable to type '{ children?: ReactNode; }'.
```

My guess is that it is related to [this change in Volto from last month](https://github.com/plone/volto/blob/main/packages/components/tsup.config.ts), as the timing of the failure and change are pretty close. @sneridagh can you enlighten us?

2024-12-05 14:57 UTC, danalvrz commented
@Tishasoumya-02 thanks for looking into this! It looks so much better already. Since you are working on it, could it be possible to implement the icon in a way that it can also be customized using the `--link-foreground-color` prop? Right now, if I want the links to be`hotpink` the icon remains blue as specified in the data URL: 

<img width="770" alt="Screenshot 2024-12-05 at 11 44 37 a m" src="https://github.com/user-attachments/assets/8f61478f-2e3e-4e78-85c7-7b8f68c29a17">

/cc @iRohitSingh @sneridagh

2024-12-06 06:16 UTC, Tishasoumya-02 commented on packages/volto-light-theme/news/439.bugfix
okay will do

2024-12-06 06:16 UTC, Tishasoumya-02 commented on packages/volto-light-theme/news/439.bugfix
> +External URL icon has strange underline fix #438  @Tishasoumya-02
ok

2024-12-06 06:16 UTC, Tishasoumya-02 commented
> @Tishasoumya-02 thanks for looking into this! It looks so much better already. Since you are working on it, could it be possible to implement the icon in a way that it can also be customized using the `--link-foreground-color` prop? Right now, if I want the links to be`hotpink` the icon remains blue as specified in the data URL:
> 
> <img alt="Screenshot 2024-12-05 at 11 44 37 a m" width="770" src="https://private-user-images.githubusercontent.com/89805481/392866320-8f61478f-2e3e-4e78-85c7-7b8f68c29a17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjU5NjUsIm5iZiI6MTczMzQ2NTY2NSwicGF0aCI6Ii84OTgwNTQ4MS8zOTI4NjYzMjAtOGY2MTQ3OGYtMmUzZS00ZTc4LTg1YzctN2I4ZjY4YzI5YTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMDU1NDBlNWE2YzUyZGFjMmZhYWJlMjRiOTk2YzU1MTJkNjgwNGIxMjQ5YzUyZjExN2ZjMDNkZWQzYWY0NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xYBdB8nyScCJnyquxYvVUbau2mEccbUzRWjyPbyKSrA">
> /cc @iRohitSingh @sneridagh

Okay will look into it.

2024-12-10 08:49 UTC, Tishasoumya-02 commented
@danalvrz , I made the changes, but I was not able to use the --link-foreground-color prop as that's a dynamic var and was not able to interpolate with the url , instead I used a static var $icon: (some color) ,and inserted in the url. Will this be okay? If you any suggestions, please let me know.

2024-12-10 09:12 UTC, stevepiercy commented
Aside from how to set the color, please consider accessibility with whatever colors you choose for links. Contrast is extremely important. Here's a decent guide for link color accessibility https://webaim.org/blog/wcag-2-0-and-link-colors/.

hotpink `#ff69b4` on white `#ffffff` is too low contrast.

https://webaim.org/resources/contrastchecker/

I also think there is some guidance about having links with different colors, except of course their active, focus, hover, visited states.

I think that having two different colors for internal and external links is unusual and may cause some accessibility issues. Unless WCAG says it is definitely OK, I would avoid it.

2024-12-10 18:32 UTC, danalvrz commented
> Aside from how to set the color, please consider accessibility with whatever colors you choose for links. Contrast is extremely important. Here's a decent guide for link color accessibility https://webaim.org/blog/wcag-2-0-and-link-colors/.
> 
> hotpink `#ff69b4` on white `#ffffff` is too low contrast.
> 
> https://webaim.org/resources/contrastchecker/
> 
> I also think there is some guidance about having links with different colors, except of course their active, focus, hover, visited states.
> 
> I think that having two different colors for internal and external links is unusual and may cause some accessibility issues. Unless WCAG says it is definitely OK, I would avoid it.

@stevepiercy yes, color contrast is very important and having a user-friendly contrast checking feature is on the list of things to work on next. Specially with the new color system. The idea is not be to have different colors for external vs internal links, but to be able to change all links to a specific color using the prop `--link-color`. It is particularly useful if, for example, you are building a site with a dark theme and need a more contrasting color for your links than the default blue.

2024-12-12 16:35 UTC, danalvrz approved these changes
@Tishasoumya-02 we should maybe update the news entry to mention the current implementation for the icon. Thanks for looking into it!

2024-12-17 02:01 UTC, stevepiercy requested changes

2024-12-17 02:01 UTC, stevepiercy commented on packages/volto-light-theme/src/theme/_variables.scss
> +    no-repeat center;
Dedent to align vertically.

```suggestion
  no-repeat center;
```

2024-12-17 02:02 UTC, stevepiercy approved these changes

2024-12-17 02:04 UTC, davisagli commented on packages/volto-light-theme/src/theme/_variables.scss
> +    no-repeat center;
@stevepiercy It was formatted this way by prettier because it's a continuation of the property from the previous line. You broke the lint check.

2024-12-17 02:05 UTC, stevepiercy commented on packages/volto-light-theme/src/theme/_variables.scss
> +    no-repeat center;
Oh, brother. Fixing.

2024-12-17 02:06 UTC, stevepiercy requested changes

2024-12-17 02:06 UTC, stevepiercy commented on packages/volto-light-theme/src/theme/_variables.scss
> +  no-repeat center;
```suggestion
    no-repeat center;
```

2024-12-17 02:06 UTC, stevepiercy approved these changes

2024-12-17 15:55 UTC, merged