PoC grid listing variaiton
kitconcept/volto-light-theme pull request #91
Opened 2023-06-08 19:25 UTC by danalvrz

2023-06-09 10:48 UTC, sneridagh approved these changes

2023-06-14 08:04 UTC, sneridagh requested changes
I'd say, let's merge it after the change I just requested.

2023-06-14 08:04 UTC, sneridagh commented on src/components/Blocks/Listing/GridTemplate.jsx
> +          const CustomItemBodyTemplate = config.getComponent({
Let's put this on the body of the component, here it falls a bit hidden.

2023-06-14 18:51 UTC, danalvrz commented on src/components/Blocks/Listing/GridTemplate.jsx
> +          const CustomItemBodyTemplate = config.getComponent({
@sneridagh just to make sure that the change I made was what you meant, before merging

2023-06-15 07:25 UTC, merged